name: 'Create Repository'
description: 'Create a new repository from your workflows.'
inputs:
  name:
    description: 'name of new repository'
    required: true
  org:
    description: 'name of an organization'
    required: false
    default: null
  access-token:
    description: 'access token with repo scope'
    required: true
  private-repo:
    description: 'is this a private repository?'
    required: false
    default: false
  initialize-repo:
    description: 'initialized repo with empty README file'
    required: false
    default: true
outputs:
  repo-id:
    description: 'GraphQL ID of newly created repository'
runs:
  using: 'node12'
  main: 'dist/index.js'
